var searchData=
[
  ['removeranimal',['removerAnimal',['../class_controlador.html#ad901745b0792e294a222ed6e07a7e4bb',1,'Controlador']]],
  ['removerfuncionario',['removerFuncionario',['../class_controlador.html#adc768cf93999572115edcd8a37fd37d3',1,'Controlador']]],
  ['reptil',['Reptil',['../class_reptil.html#ae4bc44d2a27f2506c75ad9c8c0d615e6',1,'Reptil::Reptil(int id, string classe, string classificacao, string nome_cientifico, char sexo, double tamanho, string dieta, int tem_veterinario, int tem_tratador, string nome_batismo, bool venenoso, string tipo_veneno)'],['../class_reptil.html#a8d4e391e335678b7ed64eda95e050553',1,'Reptil::Reptil()']]],
  ['reptildomestico',['ReptilDomestico',['../class_reptil_domestico.html#a20c4fbe7a8bacf30a9f831bb52e6e99b',1,'ReptilDomestico::ReptilDomestico(int id, string classe, string classificacao, string nome_cientifico, char sexo, double tamanho, string dieta, int tem_veterinario, int tem_tratador, string nome_batismo, bool venenoso, string tipo_veneno)'],['../class_reptil_domestico.html#abc6a930a37422ff5ffe05b076dac716f',1,'ReptilDomestico::ReptilDomestico()']]],
  ['reptilexotico',['ReptilExotico',['../class_reptil_exotico.html#a429bcfe479ade88d2fda42500ef5b32c',1,'ReptilExotico::ReptilExotico(int id, string classe, string classificacao, string nome_cientifico, char sexo, double tamanho, string dieta, int tem_veterinario, int tem_tratador, string nome_batismo, bool venenoso, string tipo_veneno, string autorizacao_ibama, string pais_origem, string cidade_origem)'],['../class_reptil_exotico.html#a0f9104f7cbed74d52a6711c03cd75003',1,'ReptilExotico::ReptilExotico()']]],
  ['reptilnativo',['ReptilNativo',['../class_reptil_nativo.html#a598330010952b2de3fa126b17dd24ede',1,'ReptilNativo::ReptilNativo(int id, string classe, string classificacao, string nome_cientifico, char sexo, double tamanho, string dieta, int tem_veterinario, int tem_tratador, string nome_batismo, bool venenoso, string tipo_veneno, string autorizacao_ibama, string uf_origem)'],['../class_reptil_nativo.html#a584bba0a356b2b3b961098541951fcbd',1,'ReptilNativo::ReptilNativo()']]],
  ['resolveoption',['resolveOption',['../controlador_8cpp.html#af3dec0b84b2d6da3aa3a89aca682c4b7',1,'controlador.cpp']]]
];
